name: Build

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changed files
        run: |
          changed_modules="$(git diff-tree --no-commit-id --name-only -r HEAD| grep -v -E '(\.test\.js$|jest\.config\.js$)' | awk -F/ '/^libs\//{print $2}' |uniq)"
          
          # Save the list of changed modules to an output variable
          # echo "::set-output name=changed_modules::$changed_modules"
          echo "CHANGED_MODULES=$changed_modules" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Build changed modules
        run: |
          # Loop over each module and build it if it has changed
          # for module in $CHANGED_MODULES; do
          #   (cd $GITHUB_WORKSPACE/libs/$module && npm i && npm run build)
          # done
          array=( interfaces mongodb testack )
          for module in "${array[@]}"
          do
            (cd ./libs/$module && npm i && npm run build)
          done

          (cd ./libs/create-testack/src/templates/javascript && npm i)

      # - name: execute demo test
      #   run: |
      #     cd libs/create-testack/src/templates/javascript 
      #     npm run test

      - name: execute modules tests
        run: |
          (cd libs/create-testack/src/templates/javascript && npm run test)
          npm i
          # npm run test:ci
          npm run test
